// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxFWtvh78dJ3TsSUFZ_0EqbHho4s9I4UQ',
    appId: '1:479198146234:web:48c9e806508553e1775c83',
    messagingSenderId: '479198146234',
    projectId: 'grocere-auth',
    authDomain: 'grocere-auth.firebaseapp.com',
    storageBucket: 'grocere-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIN0xt_MjHHmP6yX5ffcYzE7GAYdDE_6Q',
    appId: '1:479198146234:android:c55d428f4dcffbc4775c83',
    messagingSenderId: '479198146234',
    projectId: 'grocere-auth',
    storageBucket: 'grocere-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoR0D5O2FKjDNezOtMukTPtvgTLn_E6MI',
    appId: '1:479198146234:ios:b7a6790205961a3d775c83',
    messagingSenderId: '479198146234',
    projectId: 'grocere-auth',
    storageBucket: 'grocere-auth.appspot.com',
    iosClientId: '479198146234-8cbrolsrdm5l6q6e4qugk9hjn3ftluc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoR0D5O2FKjDNezOtMukTPtvgTLn_E6MI',
    appId: '1:479198146234:ios:b7a6790205961a3d775c83',
    messagingSenderId: '479198146234',
    projectId: 'grocere-auth',
    storageBucket: 'grocere-auth.appspot.com',
    iosClientId: '479198146234-8cbrolsrdm5l6q6e4qugk9hjn3ftluc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocere',
  );
}
